### ISSUE TITLE
still working with OPNsense 18.1.1

### ISSUE THREAD

**Issue by nin9s** [fabianfrz/logstash-filter-opnsensefilter#2]
Hi Fabian,
does this still work with the latest OPNsense 18.1.1 and ELK stack?
I've also installed your mentioned plugin "logstash-filter-opnsensefilter" and it seems to be running. Unfortunately I'm still getting "_grokparsefailure" if I try to send data to logstash

Can you give me a hint on how to debug this?

Thanks and BR from vienna ;)

**Comment by fabianfrz** [comment]
this error cannot come from this library because it is not using grok.

**Comment by nin9s** [comment]
Sorry I'm pretty new to logstash. Problem is solved, had a \n in the match pattern

**Comment by fabianfrz** [comment]
@strrrn just for your information this is a tag which grok adds in case of a problem with your regular expression. You can ignore it if you like. The main purpose of those tags is that you can make the following control flow dependent of matching data.

Delete a tag: https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-remove_tag
